# Generated by Django 5.1 on 2024-08-22 19:19

from django.db import migrations

def add_base_categories(apps, schema_editor):
    Category = apps.get_model('myapp', 'Category')
    categories = [
        'Fruits',
        'Vegetables',
        'Dairy',
        'Meat',
        'Beverages',
        'Snacks',
        'Bakery',
        'Frozen',
        'Household Items',
    ]
    for category_name in categories:
        Category.objects.create(name=category_name)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_base_categories),
    ]
