# Generated by Django 5.1 on 2024-08-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240822_1919'),
    ]

    operations = [
    ]
