# Generated by Django 5.1 on 2024-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240823_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
